export class Finance
{
id:string|undefined;
first_Name:string|undefined;
middle_Name:string|undefined;
last_Name:string|undefined;
date_of_birth:string|undefined;
phone_number:string|undefined;
email_id:string|undefined;
user_name:string|undefined;
password:string|undefined;
address:string|undefined;
card_type:string|undefined;
bank_name:string|undefined;
bank_Account_number:string|undefined;
ifs_code:string|undefined;
loginid:string|undefined;
loginpass:string|undefined;
name:string|undefined;
model_name:string|undefined;
brand_name:string|undefined;
category:string|undefined;
detail:string|undefined;
image_path:string|undefined;
cost_per_unit:string|undefined;
ID:string|undefined;
JoiningFeeStatus:string|undefined;
emicost:string|undefined;
emimonth:string|undefined;
CARDNO:string|undefined                                
BANK_ACCOUNT_NUMBER:string|undefined;                  
BANK_NAME:string|undefined;                                            
IFS_CODE:string|undefined;                                             
joiningFeeStatus:string|undefined;                                  
cardStatus:string|undefined;                                        
CARDTYPE:string|undefined;                                            
EMAIL:string|undefined;                                               
NAMEOFHOLDER:string|undefined;
orderno:string|undefined;  
limit:number|undefined;
balance:number|undefined;
email:string|undefined;
prodname:string|undefined;


}
